import React from 'react'; // Imports the React library, necessary for building React components.
import { cn } from '@/lib/utils'; // Imports the cn() function, used to dynamically concatenate, manipulate, and combine class names.
import { VariantProps, cva } from 'class-variance-authority'; 
// Imports VariantProps and cva
// VariantProps: Type automatically generated by cva to ensure proper TypeScript typing.
// cva(): Used to create dynamic CSS classes.
import { Loader2 } from 'lucide-react'; // Imports the 'Loader2' icon from the 'lucide-react' library to be used as a loading spinner icon.

// spinnerVariants defines the style variations for the spinner container.
// The cva() function creates a variant-based function with default classes to dynamically generate CSS class names.
const spinnerVariants = cva('flex-col items-center justify-center', {
  variants: {
    // Defines the visibility variants for the spinner.
    // When show is true, the spinner will have the 'flex' class and be displayed.
    // When false, it will be hidden using the 'hidden' class.
    show: {
      true: 'flex',
      false: 'hidden',
    },
  },
  defaultVariants: {
    // Sets the default value for 'show' as true.
    show: true,
  },
});

// loaderVariants defines the style variations for the loading icon.
const loaderVariants = cva('animate-spin text-white', {
  variants: {
    // Defines possible sizes for the spinner.
    size: {
      small: 'size-6',   // Small size: sets the icon size to 6.
      medium: 'size-8',  // Medium size: sets the icon size to 8.
      large: 'size-12',  // Large size: sets the icon size to 12.
    },
  },
  defaultVariants: {
    // Sets the default spinner size to large.
    size: 'large',
  },
});

// SpinnerContentProps defines the props that the Spinner component can receive.
interface SpinnerContentProps
  extends VariantProps<typeof spinnerVariants>, // Spinner visibility variants.
    VariantProps<typeof loaderVariants> { // Loader size variants.
      className?: string;   // Allows passing additional custom classes to the component.
      children?: React.ReactNode;  // Allows passing children to the component, such as text or other elements.
}

// Spinner renders the loading spinner based on the received props.
export function Spinner({ size, show, children, className }: SpinnerContentProps) {
  return (
    // The dynamic class for the spinner container is defined using spinnerVariants based on the 'show' prop.
    <span className={spinnerVariants({ show })}>
        {/* The Loader2 icon is rendered with the size defined by loaderVariants and any additional classes. */}
        <Loader2 className={cn(loaderVariants({ size }), className)} />
        {/* Renders any children passed to the component, if present. */}
        { children }
    </span>
  );
}
